// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // The table 'AdventureWorksDWBuildVersion' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // AdventureWorksDWBuildVersion
    [NotMapped]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class AdventureWorksDwBuildVersion
    {
        [Column(@"DBVersion", Order = 1, TypeName = "nvarchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Dbv ersion")]
        public string DbVersion { get; set; } // DBVersion (length: 50)

        [Column(@"VersionDate", Order = 2, TypeName = "datetime")]
        [DataType(DataType.DateTime)]
        [Display(Name = "Version date")]
        public System.DateTime? VersionDate { get; set; } // VersionDate
    }

}
// </auto-generated>
