// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // DimDate
    [Table("DimDate", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class DimDate
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"DateKey", Order = 1, TypeName = "int")]
        [Index(@"PK_DimDate_DateKey", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Date key")]
        public int DateKey { get; set; } // DateKey (Primary key)

        [Column(@"FullDateAlternateKey", Order = 2, TypeName = "date")]
        [Index(@"AK_DimDate_FullDateAlternateKey", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Full date alternate key")]
        public System.DateTime FullDateAlternateKey { get; set; } // FullDateAlternateKey

        [Column(@"DayNumberOfWeek", Order = 3, TypeName = "tinyint")]
        [Required]
        [Display(Name = "Day number of week")]
        public byte DayNumberOfWeek { get; set; } // DayNumberOfWeek

        [Column(@"EnglishDayNameOfWeek", Order = 4, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "English day name of week")]
        public string EnglishDayNameOfWeek { get; set; } // EnglishDayNameOfWeek (length: 10)

        [Column(@"SpanishDayNameOfWeek", Order = 5, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Spanish day name of week")]
        public string SpanishDayNameOfWeek { get; set; } // SpanishDayNameOfWeek (length: 10)

        [Column(@"FrenchDayNameOfWeek", Order = 6, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "French day name of week")]
        public string FrenchDayNameOfWeek { get; set; } // FrenchDayNameOfWeek (length: 10)

        [Column(@"DayNumberOfMonth", Order = 7, TypeName = "tinyint")]
        [Required]
        [Display(Name = "Day number of month")]
        public byte DayNumberOfMonth { get; set; } // DayNumberOfMonth

        [Column(@"DayNumberOfYear", Order = 8, TypeName = "smallint")]
        [Required]
        [Display(Name = "Day number of year")]
        public short DayNumberOfYear { get; set; } // DayNumberOfYear

        [Column(@"WeekNumberOfYear", Order = 9, TypeName = "tinyint")]
        [Required]
        [Display(Name = "Week number of year")]
        public byte WeekNumberOfYear { get; set; } // WeekNumberOfYear

        [Column(@"EnglishMonthName", Order = 10, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "English month name")]
        public string EnglishMonthName { get; set; } // EnglishMonthName (length: 10)

        [Column(@"SpanishMonthName", Order = 11, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Spanish month name")]
        public string SpanishMonthName { get; set; } // SpanishMonthName (length: 10)

        [Column(@"FrenchMonthName", Order = 12, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "French month name")]
        public string FrenchMonthName { get; set; } // FrenchMonthName (length: 10)

        [Column(@"MonthNumberOfYear", Order = 13, TypeName = "tinyint")]
        [Required]
        [Display(Name = "Month number of year")]
        public byte MonthNumberOfYear { get; set; } // MonthNumberOfYear

        [Column(@"CalendarQuarter", Order = 14, TypeName = "tinyint")]
        [Required]
        [Display(Name = "Calendar quarter")]
        public byte CalendarQuarter { get; set; } // CalendarQuarter

        [Column(@"CalendarYear", Order = 15, TypeName = "smallint")]
        [Required]
        [Display(Name = "Calendar year")]
        public short CalendarYear { get; set; } // CalendarYear

        [Column(@"CalendarSemester", Order = 16, TypeName = "tinyint")]
        [Required]
        [Display(Name = "Calendar semester")]
        public byte CalendarSemester { get; set; } // CalendarSemester

        [Column(@"FiscalQuarter", Order = 17, TypeName = "tinyint")]
        [Required]
        [Display(Name = "Fiscal quarter")]
        public byte FiscalQuarter { get; set; } // FiscalQuarter

        [Column(@"FiscalYear", Order = 18, TypeName = "smallint")]
        [Required]
        [Display(Name = "Fiscal year")]
        public short FiscalYear { get; set; } // FiscalYear

        [Column(@"FiscalSemester", Order = 19, TypeName = "tinyint")]
        [Required]
        [Display(Name = "Fiscal semester")]
        public byte FiscalSemester { get; set; } // FiscalSemester

        // Reverse navigation

        /// <summary>
        /// Child FactCallCenters where [FactCallCenter].[DateKey] point to this entity (FK_FactCallCenter_DimDate)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FactCallCenter> FactCallCenters { get; set; } // FactCallCenter.FK_FactCallCenter_DimDate
        /// <summary>
        /// Child FactCurrencyRates where [FactCurrencyRate].[DateKey] point to this entity (FK_FactCurrencyRate_DimDate)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FactCurrencyRate> FactCurrencyRates { get; set; } // FactCurrencyRate.FK_FactCurrencyRate_DimDate
        /// <summary>
        /// Child FactFinances where [FactFinance].[DateKey] point to this entity (FK_FactFinance_DimDate)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FactFinance> FactFinances { get; set; } // FactFinance.FK_FactFinance_DimDate
        /// <summary>
        /// Child FactInternetSales where [FactInternetSales].[DueDateKey] point to this entity (FK_FactInternetSales_DimDate1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FactInternetSale> FactInternetSales_DueDateKey { get; set; } // FactInternetSales.FK_FactInternetSales_DimDate1
        /// <summary>
        /// Child FactInternetSales where [FactInternetSales].[OrderDateKey] point to this entity (FK_FactInternetSales_DimDate)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FactInternetSale> FactInternetSales_OrderDateKey { get; set; } // FactInternetSales.FK_FactInternetSales_DimDate
        /// <summary>
        /// Child FactInternetSales where [FactInternetSales].[ShipDateKey] point to this entity (FK_FactInternetSales_DimDate2)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FactInternetSale> FactInternetSales_ShipDateKey { get; set; } // FactInternetSales.FK_FactInternetSales_DimDate2
        /// <summary>
        /// Child FactProductInventories where [FactProductInventory].[DateKey] point to this entity (FK_FactProductInventory_DimDate)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FactProductInventory> FactProductInventories { get; set; } // FactProductInventory.FK_FactProductInventory_DimDate
        /// <summary>
        /// Child FactResellerSales where [FactResellerSales].[DueDateKey] point to this entity (FK_FactResellerSales_DimDate1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FactResellerSale> FactResellerSales_DueDateKey { get; set; } // FactResellerSales.FK_FactResellerSales_DimDate1
        /// <summary>
        /// Child FactResellerSales where [FactResellerSales].[OrderDateKey] point to this entity (FK_FactResellerSales_DimDate)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FactResellerSale> FactResellerSales_OrderDateKey { get; set; } // FactResellerSales.FK_FactResellerSales_DimDate
        /// <summary>
        /// Child FactResellerSales where [FactResellerSales].[ShipDateKey] point to this entity (FK_FactResellerSales_DimDate2)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FactResellerSale> FactResellerSales_ShipDateKey { get; set; } // FactResellerSales.FK_FactResellerSales_DimDate2
        /// <summary>
        /// Child FactSalesQuotas where [FactSalesQuota].[DateKey] point to this entity (FK_FactSalesQuota_DimDate)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FactSalesQuota> FactSalesQuotas { get; set; } // FactSalesQuota.FK_FactSalesQuota_DimDate
        /// <summary>
        /// Child FactSurveyResponses where [FactSurveyResponse].[DateKey] point to this entity (FK_FactSurveyResponse_DateKey)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FactSurveyResponse> FactSurveyResponses { get; set; } // FactSurveyResponse.FK_FactSurveyResponse_DateKey

        public DimDate()
        {
            FactCallCenters = new System.Collections.Generic.List<FactCallCenter>();
            FactCurrencyRates = new System.Collections.Generic.List<FactCurrencyRate>();
            FactFinances = new System.Collections.Generic.List<FactFinance>();
            FactInternetSales_DueDateKey = new System.Collections.Generic.List<FactInternetSale>();
            FactInternetSales_OrderDateKey = new System.Collections.Generic.List<FactInternetSale>();
            FactInternetSales_ShipDateKey = new System.Collections.Generic.List<FactInternetSale>();
            FactProductInventories = new System.Collections.Generic.List<FactProductInventory>();
            FactResellerSales_DueDateKey = new System.Collections.Generic.List<FactResellerSale>();
            FactResellerSales_OrderDateKey = new System.Collections.Generic.List<FactResellerSale>();
            FactResellerSales_ShipDateKey = new System.Collections.Generic.List<FactResellerSale>();
            FactSalesQuotas = new System.Collections.Generic.List<FactSalesQuota>();
            FactSurveyResponses = new System.Collections.Generic.List<FactSurveyResponse>();
        }
    }

}
// </auto-generated>
