// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // DimDepartmentGroup
    [Table("DimDepartmentGroup", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class DimDepartmentGroup
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"DepartmentGroupKey", Order = 1, TypeName = "int")]
        [Index(@"PK_DimDepartmentGroup", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Department group key")]
        public int DepartmentGroupKey { get; set; } // DepartmentGroupKey (Primary key)

        [Column(@"ParentDepartmentGroupKey", Order = 2, TypeName = "int")]
        [Display(Name = "Parent department group key")]
        public int? ParentDepartmentGroupKey { get; set; } // ParentDepartmentGroupKey

        [Column(@"DepartmentGroupName", Order = 3, TypeName = "nvarchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Department group name")]
        public string DepartmentGroupName { get; set; } // DepartmentGroupName (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child DimDepartmentGroups where [DimDepartmentGroup].[ParentDepartmentGroupKey] point to this entity (FK_DimDepartmentGroup_DimDepartmentGroup)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<DimDepartmentGroup> DimDepartmentGroups { get; set; } // DimDepartmentGroup.FK_DimDepartmentGroup_DimDepartmentGroup
        /// <summary>
        /// Child FactFinances where [FactFinance].[DepartmentGroupKey] point to this entity (FK_FactFinance_DimDepartmentGroup)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FactFinance> FactFinances { get; set; } // FactFinance.FK_FactFinance_DimDepartmentGroup

        // Foreign keys

        /// <summary>
        /// Parent DimDepartmentGroup pointed by [DimDepartmentGroup].([ParentDepartmentGroupKey]) (FK_DimDepartmentGroup_DimDepartmentGroup)
        /// </summary>
        [ForeignKey("ParentDepartmentGroupKey")] public virtual DimDepartmentGroup DimDepartmentGroup_ParentDepartmentGroupKey { get; set; } // FK_DimDepartmentGroup_DimDepartmentGroup

        public DimDepartmentGroup()
        {
            DimDepartmentGroups = new System.Collections.Generic.List<DimDepartmentGroup>();
            FactFinances = new System.Collections.Generic.List<FactFinance>();
        }
    }

}
// </auto-generated>
