// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // DimProductCategory
    [Table("DimProductCategory", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class DimProductCategory
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ProductCategoryKey", Order = 1, TypeName = "int")]
        [Index(@"PK_DimProductCategory_ProductCategoryKey", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Product category key")]
        public int ProductCategoryKey { get; set; } // ProductCategoryKey (Primary key)

        [Column(@"ProductCategoryAlternateKey", Order = 2, TypeName = "int")]
        [Index(@"AK_DimProductCategory_ProductCategoryAlternateKey", 1, IsUnique = true, IsClustered = false)]
        [Display(Name = "Product category alternate key")]
        public int? ProductCategoryAlternateKey { get; set; } // ProductCategoryAlternateKey

        [Column(@"EnglishProductCategoryName", Order = 3, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "English product category name")]
        public string EnglishProductCategoryName { get; set; } // EnglishProductCategoryName (length: 50)

        [Column(@"SpanishProductCategoryName", Order = 4, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Spanish product category name")]
        public string SpanishProductCategoryName { get; set; } // SpanishProductCategoryName (length: 50)

        [Column(@"FrenchProductCategoryName", Order = 5, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "French product category name")]
        public string FrenchProductCategoryName { get; set; } // FrenchProductCategoryName (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child DimProductSubcategories where [DimProductSubcategory].[ProductCategoryKey] point to this entity (FK_DimProductSubcategory_DimProductCategory)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<DimProductSubcategory> DimProductSubcategories { get; set; } // DimProductSubcategory.FK_DimProductSubcategory_DimProductCategory

        public DimProductCategory()
        {
            DimProductSubcategories = new System.Collections.Generic.List<DimProductSubcategory>();
        }
    }

}
// </auto-generated>
