// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // DimSalesReason
    [Table("DimSalesReason", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class DimSalesReason
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"SalesReasonKey", Order = 1, TypeName = "int")]
        [Index(@"PK_DimSalesReason_SalesReasonKey", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Sales reason key")]
        public int SalesReasonKey { get; set; } // SalesReasonKey (Primary key)

        [Column(@"SalesReasonAlternateKey", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Sales reason alternate key")]
        public int SalesReasonAlternateKey { get; set; } // SalesReasonAlternateKey

        [Column(@"SalesReasonName", Order = 3, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Sales reason name")]
        public string SalesReasonName { get; set; } // SalesReasonName (length: 50)

        [Column(@"SalesReasonReasonType", Order = 4, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Sales reason reason type")]
        public string SalesReasonReasonType { get; set; } // SalesReasonReasonType (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child FactInternetSalesReasons where [FactInternetSalesReason].[SalesReasonKey] point to this entity (FK_FactInternetSalesReason_DimSalesReason)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FactInternetSalesReason> FactInternetSalesReasons { get; set; } // FactInternetSalesReason.FK_FactInternetSalesReason_DimSalesReason

        public DimSalesReason()
        {
            FactInternetSalesReasons = new System.Collections.Generic.List<FactInternetSalesReason>();
        }
    }

}
// </auto-generated>
