// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // DimScenario
    [Table("DimScenario", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class DimScenario
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ScenarioKey", Order = 1, TypeName = "int")]
        [Index(@"PK_DimScenario", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Scenario key")]
        public int ScenarioKey { get; set; } // ScenarioKey (Primary key)

        [Column(@"ScenarioName", Order = 2, TypeName = "nvarchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Scenario name")]
        public string ScenarioName { get; set; } // ScenarioName (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child FactFinances where [FactFinance].[ScenarioKey] point to this entity (FK_FactFinance_DimScenario)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FactFinance> FactFinances { get; set; } // FactFinance.FK_FactFinance_DimScenario

        public DimScenario()
        {
            FactFinances = new System.Collections.Generic.List<FactFinance>();
        }
    }

}
// </auto-generated>
