// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // FactInternetSales
    [Table("FactInternetSales", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class FactInternetSale
    {
        [Column(@"ProductKey", Order = 1, TypeName = "int")]
        [Required]
        [Display(Name = "Product key")]
        public int ProductKey { get; set; } // ProductKey

        [Column(@"OrderDateKey", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Order date key")]
        public int OrderDateKey { get; set; } // OrderDateKey

        [Column(@"DueDateKey", Order = 3, TypeName = "int")]
        [Required]
        [Display(Name = "Due date key")]
        public int DueDateKey { get; set; } // DueDateKey

        [Column(@"ShipDateKey", Order = 4, TypeName = "int")]
        [Required]
        [Display(Name = "Ship date key")]
        public int ShipDateKey { get; set; } // ShipDateKey

        [Column(@"CustomerKey", Order = 5, TypeName = "int")]
        [Required]
        [Display(Name = "Customer key")]
        public int CustomerKey { get; set; } // CustomerKey

        [Column(@"PromotionKey", Order = 6, TypeName = "int")]
        [Required]
        [Display(Name = "Promotion key")]
        public int PromotionKey { get; set; } // PromotionKey

        [Column(@"CurrencyKey", Order = 7, TypeName = "int")]
        [Required]
        [Display(Name = "Currency key")]
        public int CurrencyKey { get; set; } // CurrencyKey

        [Column(@"SalesTerritoryKey", Order = 8, TypeName = "int")]
        [Required]
        [Display(Name = "Sales territory key")]
        public int SalesTerritoryKey { get; set; } // SalesTerritoryKey

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"SalesOrderNumber", Order = 9, TypeName = "nvarchar")]
        [Index(@"PK_FactInternetSales_SalesOrderNumber_SalesOrderLineNumber", 1, IsUnique = true, IsClustered = true)]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(20)]
        [StringLength(20)]
        [Key]
        [Display(Name = "Sales order number")]
        public string SalesOrderNumber { get; set; } // SalesOrderNumber (Primary key) (length: 20)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"SalesOrderLineNumber", Order = 10, TypeName = "tinyint")]
        [Index(@"PK_FactInternetSales_SalesOrderNumber_SalesOrderLineNumber", 2, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Sales order line number")]
        public byte SalesOrderLineNumber { get; set; } // SalesOrderLineNumber (Primary key)

        [Column(@"RevisionNumber", Order = 11, TypeName = "tinyint")]
        [Required]
        [Display(Name = "Revision number")]
        public byte RevisionNumber { get; set; } // RevisionNumber

        [Column(@"OrderQuantity", Order = 12, TypeName = "smallint")]
        [Required]
        [Display(Name = "Order quantity")]
        public short OrderQuantity { get; set; } // OrderQuantity

        [Column(@"UnitPrice", Order = 13, TypeName = "money")]
        [Required]
        [DataType(DataType.Currency)]
        [Display(Name = "Unit price")]
        public decimal UnitPrice { get; set; } // UnitPrice

        [Column(@"ExtendedAmount", Order = 14, TypeName = "money")]
        [Required]
        [DataType(DataType.Currency)]
        [Display(Name = "Extended amount")]
        public decimal ExtendedAmount { get; set; } // ExtendedAmount

        [Column(@"UnitPriceDiscountPct", Order = 15, TypeName = "float")]
        [Required]
        [Display(Name = "Unit price discount pct")]
        public double UnitPriceDiscountPct { get; set; } // UnitPriceDiscountPct

        [Column(@"DiscountAmount", Order = 16, TypeName = "float")]
        [Required]
        [Display(Name = "Discount amount")]
        public double DiscountAmount { get; set; } // DiscountAmount

        [Column(@"ProductStandardCost", Order = 17, TypeName = "money")]
        [Required]
        [DataType(DataType.Currency)]
        [Display(Name = "Product standard cost")]
        public decimal ProductStandardCost { get; set; } // ProductStandardCost

        [Column(@"TotalProductCost", Order = 18, TypeName = "money")]
        [Required]
        [DataType(DataType.Currency)]
        [Display(Name = "Total product cost")]
        public decimal TotalProductCost { get; set; } // TotalProductCost

        [Column(@"SalesAmount", Order = 19, TypeName = "money")]
        [Required]
        [DataType(DataType.Currency)]
        [Display(Name = "Sales amount")]
        public decimal SalesAmount { get; set; } // SalesAmount

        [Column(@"TaxAmt", Order = 20, TypeName = "money")]
        [Required]
        [DataType(DataType.Currency)]
        [Display(Name = "Tax amt")]
        public decimal TaxAmt { get; set; } // TaxAmt

        [Column(@"Freight", Order = 21, TypeName = "money")]
        [Required]
        [DataType(DataType.Currency)]
        [Display(Name = "Freight")]
        public decimal Freight { get; set; } // Freight

        [Column(@"CarrierTrackingNumber", Order = 22, TypeName = "nvarchar")]
        [MaxLength(25)]
        [StringLength(25)]
        [Display(Name = "Carrier tracking number")]
        public string CarrierTrackingNumber { get; set; } // CarrierTrackingNumber (length: 25)

        [Column(@"CustomerPONumber", Order = 23, TypeName = "nvarchar")]
        [MaxLength(25)]
        [StringLength(25)]
        [Display(Name = "Customer pon umber")]
        public string CustomerPoNumber { get; set; } // CustomerPONumber (length: 25)

        [Column(@"OrderDate", Order = 24, TypeName = "datetime")]
        [DataType(DataType.DateTime)]
        [Display(Name = "Order date")]
        public System.DateTime? OrderDate { get; set; } // OrderDate

        [Column(@"DueDate", Order = 25, TypeName = "datetime")]
        [DataType(DataType.DateTime)]
        [Display(Name = "Due date")]
        public System.DateTime? DueDate { get; set; } // DueDate

        [Column(@"ShipDate", Order = 26, TypeName = "datetime")]
        [DataType(DataType.DateTime)]
        [Display(Name = "Ship date")]
        public System.DateTime? ShipDate { get; set; } // ShipDate

        // Reverse navigation

        /// <summary>
        /// Child FactInternetSalesReasons where [FactInternetSalesReason].([SalesOrderLineNumber], [SalesOrderNumber]) point to this entity (FK_FactInternetSalesReason_FactInternetSales)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<FactInternetSalesReason> FactInternetSalesReasons { get; set; } // FactInternetSalesReason.FK_FactInternetSalesReason_FactInternetSales

        // Foreign keys

        /// <summary>
        /// Parent DimCurrency pointed by [FactInternetSales].([CurrencyKey]) (FK_FactInternetSales_DimCurrency)
        /// </summary>
        [ForeignKey("CurrencyKey"), Required] public virtual DimCurrency DimCurrency { get; set; } // FK_FactInternetSales_DimCurrency

        /// <summary>
        /// Parent DimCustomer pointed by [FactInternetSales].([CustomerKey]) (FK_FactInternetSales_DimCustomer)
        /// </summary>
        [ForeignKey("CustomerKey"), Required] public virtual DimCustomer DimCustomer { get; set; } // FK_FactInternetSales_DimCustomer

        /// <summary>
        /// Parent DimDate pointed by [FactInternetSales].([DueDateKey]) (FK_FactInternetSales_DimDate1)
        /// </summary>
        [ForeignKey("DueDateKey"), Required] public virtual DimDate DimDate_DueDateKey { get; set; } // FK_FactInternetSales_DimDate1

        /// <summary>
        /// Parent DimDate pointed by [FactInternetSales].([OrderDateKey]) (FK_FactInternetSales_DimDate)
        /// </summary>
        [ForeignKey("OrderDateKey"), Required] public virtual DimDate DimDate_OrderDateKey { get; set; } // FK_FactInternetSales_DimDate

        /// <summary>
        /// Parent DimProduct pointed by [FactInternetSales].([ProductKey]) (FK_FactInternetSales_DimProduct)
        /// </summary>
        [ForeignKey("ProductKey"), Required] public virtual DimProduct DimProduct { get; set; } // FK_FactInternetSales_DimProduct

        /// <summary>
        /// Parent DimPromotion pointed by [FactInternetSales].([PromotionKey]) (FK_FactInternetSales_DimPromotion)
        /// </summary>
        [ForeignKey("PromotionKey"), Required] public virtual DimPromotion DimPromotion { get; set; } // FK_FactInternetSales_DimPromotion

        /// <summary>
        /// Parent DimSalesTerritory pointed by [FactInternetSales].([SalesTerritoryKey]) (FK_FactInternetSales_DimSalesTerritory)
        /// </summary>
        [ForeignKey("SalesTerritoryKey"), Required] public virtual DimSalesTerritory DimSalesTerritory { get; set; } // FK_FactInternetSales_DimSalesTerritory

        /// <summary>
        /// Parent DimDate pointed by [FactInternetSales].([ShipDateKey]) (FK_FactInternetSales_DimDate2)
        /// </summary>
        [ForeignKey("ShipDateKey"), Required] public virtual DimDate DimDate_ShipDateKey { get; set; } // FK_FactInternetSales_DimDate2

        public FactInternetSale()
        {
            FactInternetSalesReasons = new System.Collections.Generic.List<FactInternetSalesReason>();
        }
    }

}
// </auto-generated>
