// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // FactProductInventory
    [Table("FactProductInventory", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class FactProductInventory
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ProductKey", Order = 1, TypeName = "int")]
        [Index(@"PK_FactProductInventory", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Product key")]
        public int ProductKey { get; set; } // ProductKey (Primary key)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"DateKey", Order = 2, TypeName = "int")]
        [Index(@"PK_FactProductInventory", 2, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Date key")]
        public int DateKey { get; set; } // DateKey (Primary key)

        [Column(@"MovementDate", Order = 3, TypeName = "date")]
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Movement date")]
        public System.DateTime MovementDate { get; set; } // MovementDate

        [Column(@"UnitCost", Order = 4, TypeName = "money")]
        [Required]
        [DataType(DataType.Currency)]
        [Display(Name = "Unit cost")]
        public decimal UnitCost { get; set; } // UnitCost

        [Column(@"UnitsIn", Order = 5, TypeName = "int")]
        [Required]
        [Display(Name = "Units in")]
        public int UnitsIn { get; set; } // UnitsIn

        [Column(@"UnitsOut", Order = 6, TypeName = "int")]
        [Required]
        [Display(Name = "Units out")]
        public int UnitsOut { get; set; } // UnitsOut

        [Column(@"UnitsBalance", Order = 7, TypeName = "int")]
        [Required]
        [Display(Name = "Units balance")]
        public int UnitsBalance { get; set; } // UnitsBalance

        // Foreign keys

        /// <summary>
        /// Parent DimDate pointed by [FactProductInventory].([DateKey]) (FK_FactProductInventory_DimDate)
        /// </summary>
        [ForeignKey("DateKey"), Required] public virtual DimDate DimDate { get; set; } // FK_FactProductInventory_DimDate

        /// <summary>
        /// Parent DimProduct pointed by [FactProductInventory].([ProductKey]) (FK_FactProductInventory_DimProduct)
        /// </summary>
        [ForeignKey("ProductKey"), Required] public virtual DimProduct DimProduct { get; set; } // FK_FactProductInventory_DimProduct
    }

}
// </auto-generated>
