// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // FactAdditionalInternationalProductDescription
    [Table("FactAdditionalInternationalProductDescription", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class FactAdditionalInternationalProductDescription
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ProductKey", Order = 1, TypeName = "int")]
        [Index(@"PK_FactAdditionalInternationalProductDescription_ProductKey_CultureName", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Product key")]
        public int ProductKey { get; set; } // ProductKey (Primary key)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"CultureName", Order = 2, TypeName = "nvarchar")]
        [Index(@"PK_FactAdditionalInternationalProductDescription_ProductKey_CultureName", 2, IsUnique = true, IsClustered = true)]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Key]
        [Display(Name = "Culture name")]
        public string CultureName { get; set; } // CultureName (Primary key) (length: 50)

        [Column(@"ProductDescription", Order = 3, TypeName = "nvarchar(max)")]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Product description")]
        public string ProductDescription { get; set; } // ProductDescription
    }

}
// </auto-generated>
