// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // The table 'NewFactCurrencyRate' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // NewFactCurrencyRate
    [NotMapped]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class NewFactCurrencyRate
    {
        [Column(@"AverageRate", Order = 1, TypeName = "real")]
        [Display(Name = "Average rate")]
        public float? AverageRate { get; set; } // AverageRate

        [Column(@"CurrencyID", Order = 2, TypeName = "nvarchar")]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Currency ID")]
        public string CurrencyId { get; set; } // CurrencyID (length: 3)

        [Column(@"CurrencyDate", Order = 3, TypeName = "date")]
        [DataType(DataType.Date)]
        [Display(Name = "Currency date")]
        public System.DateTime? CurrencyDate { get; set; } // CurrencyDate

        [Column(@"EndOfDayRate", Order = 4, TypeName = "real")]
        [Display(Name = "End of day rate")]
        public float? EndOfDayRate { get; set; } // EndOfDayRate

        [Column(@"CurrencyKey", Order = 5, TypeName = "int")]
        [Display(Name = "Currency key")]
        public int? CurrencyKey { get; set; } // CurrencyKey

        [Column(@"DateKey", Order = 6, TypeName = "int")]
        [Display(Name = "Date key")]
        public int? DateKey { get; set; } // DateKey
    }

}
// </auto-generated>
