// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // vAssocSeqLineItems
    [Table("vAssocSeqLineItems", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class VAssocSeqLineItem
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"OrderNumber", Order = 1, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(20)]
        [StringLength(20)]
        [Key]
        [Display(Name = "Order number")]
        public string OrderNumber { get; set; } // OrderNumber (Primary key) (length: 20)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"LineNumber", Order = 2, TypeName = "tinyint")]
        [Required]
        [Key]
        [Display(Name = "Line number")]
        public byte LineNumber { get; set; } // LineNumber (Primary key)

        [Column(@"Model", Order = 3, TypeName = "nvarchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Model")]
        public string Model { get; set; } // Model (length: 50)
    }

}
// </auto-generated>
