// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // vAssocSeqOrders
    [Table("vAssocSeqOrders", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class VAssocSeqOrder
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"OrderNumber", Order = 1, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(20)]
        [StringLength(20)]
        [Key]
        [Display(Name = "Order number")]
        public string OrderNumber { get; set; } // OrderNumber (Primary key) (length: 20)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"CustomerKey", Order = 2, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Customer key")]
        public int CustomerKey { get; set; } // CustomerKey (Primary key)

        [Column(@"Region", Order = 3, TypeName = "nvarchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Region")]
        public string Region { get; set; } // Region (length: 50)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"IncomeGroup", Order = 4, TypeName = "varchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(8)]
        [StringLength(8)]
        [Key]
        [Display(Name = "Income group")]
        public string IncomeGroup { get; set; } // IncomeGroup (Primary key) (length: 8)
    }

}
// </auto-generated>
