// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Configurations
{
    using Entities;
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // DimAccount
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class DimAccountConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DimAccount>
    {
        public DimAccountConfiguration()
            : this("dbo")
        {
        }

        public DimAccountConfiguration(string schema)
        {
            Property(x => x.ParentAccountKey).IsOptional();
            Property(x => x.AccountCodeAlternateKey).IsOptional();
            Property(x => x.ParentAccountCodeAlternateKey).IsOptional();
            Property(x => x.AccountDescription).IsOptional();
            Property(x => x.AccountType).IsOptional();
            Property(x => x.Operator).IsOptional();
            Property(x => x.CustomMembers).IsOptional();
            Property(x => x.ValueType).IsOptional();
            Property(x => x.CustomMemberOptions).IsOptional();

        }
    }

}
// </auto-generated>
