// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Configurations
{
    using Entities;
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // DimEmployee
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class DimEmployeeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DimEmployee>
    {
        public DimEmployeeConfiguration()
            : this("dbo")
        {
        }

        public DimEmployeeConfiguration(string schema)
        {
            Property(x => x.ParentEmployeeKey).IsOptional();
            Property(x => x.EmployeeNationalIdAlternateKey).IsOptional();
            Property(x => x.ParentEmployeeNationalIdAlternateKey).IsOptional();
            Property(x => x.SalesTerritoryKey).IsOptional();
            Property(x => x.MiddleName).IsOptional();
            Property(x => x.Title).IsOptional();
            Property(x => x.HireDate).IsOptional();
            Property(x => x.BirthDate).IsOptional();
            Property(x => x.LoginId).IsOptional();
            Property(x => x.EmailAddress).IsOptional();
            Property(x => x.Phone).IsOptional();
            Property(x => x.MaritalStatus).IsOptional().IsFixedLength();
            Property(x => x.EmergencyContactName).IsOptional();
            Property(x => x.EmergencyContactPhone).IsOptional();
            Property(x => x.SalariedFlag).IsOptional();
            Property(x => x.Gender).IsOptional().IsFixedLength();
            Property(x => x.PayFrequency).IsOptional();
            Property(x => x.BaseRate).IsOptional().HasPrecision(19,4);
            Property(x => x.VacationHours).IsOptional();
            Property(x => x.SickLeaveHours).IsOptional();
            Property(x => x.DepartmentName).IsOptional();
            Property(x => x.StartDate).IsOptional();
            Property(x => x.EndDate).IsOptional();
            Property(x => x.Status).IsOptional();
            Property(x => x.EmployeePhoto).IsOptional();

        }
    }

}
// </auto-generated>
