// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Configurations
{
    using Entities;
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // DimPromotion
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class DimPromotionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DimPromotion>
    {
        public DimPromotionConfiguration()
            : this("dbo")
        {
        }

        public DimPromotionConfiguration(string schema)
        {
            Property(x => x.PromotionAlternateKey).IsOptional();
            Property(x => x.EnglishPromotionName).IsOptional();
            Property(x => x.SpanishPromotionName).IsOptional();
            Property(x => x.FrenchPromotionName).IsOptional();
            Property(x => x.DiscountPct).IsOptional();
            Property(x => x.EnglishPromotionType).IsOptional();
            Property(x => x.SpanishPromotionType).IsOptional();
            Property(x => x.FrenchPromotionType).IsOptional();
            Property(x => x.EnglishPromotionCategory).IsOptional();
            Property(x => x.SpanishPromotionCategory).IsOptional();
            Property(x => x.FrenchPromotionCategory).IsOptional();
            Property(x => x.EndDate).IsOptional();
            Property(x => x.MinQty).IsOptional();
            Property(x => x.MaxQty).IsOptional();
        }
    }

}
// </auto-generated>
