// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Configurations
{
    using Entities;
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // DimReseller
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class DimResellerConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DimReseller>
    {
        public DimResellerConfiguration()
            : this("dbo")
        {
        }

        public DimResellerConfiguration(string schema)
        {
            Property(x => x.GeographyKey).IsOptional();
            Property(x => x.ResellerAlternateKey).IsOptional();
            Property(x => x.Phone).IsOptional();
            Property(x => x.BusinessType).IsUnicode(false);
            Property(x => x.NumberEmployees).IsOptional();
            Property(x => x.OrderFrequency).IsOptional().IsFixedLength().IsUnicode(false);
            Property(x => x.OrderMonth).IsOptional();
            Property(x => x.FirstOrderYear).IsOptional();
            Property(x => x.LastOrderYear).IsOptional();
            Property(x => x.ProductLine).IsOptional();
            Property(x => x.AddressLine1).IsOptional();
            Property(x => x.AddressLine2).IsOptional();
            Property(x => x.AnnualSales).IsOptional().HasPrecision(19,4);
            Property(x => x.BankName).IsOptional();
            Property(x => x.MinPaymentType).IsOptional();
            Property(x => x.MinPaymentAmount).IsOptional().HasPrecision(19,4);
            Property(x => x.AnnualRevenue).IsOptional().HasPrecision(19,4);
            Property(x => x.YearOpened).IsOptional();

        }
    }

}
// </auto-generated>
