// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Configurations
{
    using Entities;
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // FactResellerSales
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class FactResellerSaleConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<FactResellerSale>
    {
        public FactResellerSaleConfiguration()
            : this("dbo")
        {
        }

        public FactResellerSaleConfiguration(string schema)
        {
            Property(x => x.RevisionNumber).IsOptional();
            Property(x => x.OrderQuantity).IsOptional();
            Property(x => x.UnitPrice).IsOptional().HasPrecision(19,4);
            Property(x => x.ExtendedAmount).IsOptional().HasPrecision(19,4);
            Property(x => x.UnitPriceDiscountPct).IsOptional();
            Property(x => x.DiscountAmount).IsOptional();
            Property(x => x.ProductStandardCost).IsOptional().HasPrecision(19,4);
            Property(x => x.TotalProductCost).IsOptional().HasPrecision(19,4);
            Property(x => x.SalesAmount).IsOptional().HasPrecision(19,4);
            Property(x => x.TaxAmt).IsOptional().HasPrecision(19,4);
            Property(x => x.Freight).IsOptional().HasPrecision(19,4);
            Property(x => x.CarrierTrackingNumber).IsOptional();
            Property(x => x.CustomerPoNumber).IsOptional();
            Property(x => x.OrderDate).IsOptional();
            Property(x => x.DueDate).IsOptional();
            Property(x => x.ShipDate).IsOptional();

        }
    }

}
// </auto-generated>
