// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Configurations
{
    using Entities;
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // FactInternetSales
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class FactInternetSaleConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<FactInternetSale>
    {
        public FactInternetSaleConfiguration()
            : this("dbo")
        {
        }

        public FactInternetSaleConfiguration(string schema)
        {
            Property(x => x.UnitPrice).HasPrecision(19,4);
            Property(x => x.ExtendedAmount).HasPrecision(19,4);
            Property(x => x.ProductStandardCost).HasPrecision(19,4);
            Property(x => x.TotalProductCost).HasPrecision(19,4);
            Property(x => x.SalesAmount).HasPrecision(19,4);
            Property(x => x.TaxAmt).HasPrecision(19,4);
            Property(x => x.Freight).HasPrecision(19,4);
            Property(x => x.CarrierTrackingNumber).IsOptional();
            Property(x => x.CustomerPoNumber).IsOptional();
            Property(x => x.OrderDate).IsOptional();
            Property(x => x.DueDate).IsOptional();
            Property(x => x.ShipDate).IsOptional();

        }
    }

}
// </auto-generated>
